version: "3"

services:
  label-studio:
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - PORT=${PORT}
    container_name: ${PROJECT_NAME}
    image: ${PROJECT_NAME}:latest
    build:
      context: .
      dockerfile: ./Dockerfile

    working_dir: /label-studio
    ports:
      - "${PORT}:${PORT}"
    restart: always
